import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { NextAuthProvider } from "../../Providers";
import Header from "../../components/Header";
import Footer from "../../components/Footer";

import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Akaltrip",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <NextAuthProvider>
      <html lang="en" suppressHydrationWarning>
        <body
          className={`flex flex-col min-h-screen ${geistSans.variable} ${geistMono.variable} mx-auto antialiased`}
        >
          <Header />
          <main className="flex-1">{children}</main>
          <Link className=" cursor-pointer" href={'/ai-assistant'}>
            <button className="fixed bottom-6 cursor-pointer right-6 z-50 px-4 py-2 bg-blue-600 text-white rounded-full shadow-lg hover:bg-blue-700 transition">
              AI ASSISTANT
            </button>
          </Link>
        </body>
      </html>
    </NextAuthProvider>
  );
}
